"""Gate 0b/0c/0d micro-experiment: is classical simulability encoding-relative?

For the SAME fermionic object under JW / BK / parity encodings, test the predicted split:
  - DLA dimension   -> INVARIANT  (encodings are Clifford-equivalent; DLA is Clifford-invariant)
  - magic (2-SRE)   -> INVARIANT  (Clifford-invariant)
  - Pauli weight    -> COVARIANT  (JW ~ O(n) strings vs BK/parity ~ O(log n))
and whether the weight-based simulability verdict FLIPS across encodings (the substance gate).

Run: python gauge_micro.py
"""
import numpy as np
import openfermion as of
from openfermion import FermionOperator, jordan_wigner, bravyi_kitaev, get_sparse_operator

# compat: newer numpy makes (-1)**int64 a numpy.int64; older openfermion type-checks reject it.
# Run in every process (joblib/loky workers don't inherit it); guarded -> one-time no-op.
def _ofpatch():
    import openfermion.ops.operators.symbolic_operator as _s
    if not isinstance(np.int64(0), _s.COEFFICIENT_TYPES):
        _s.COEFFICIENT_TYPES = tuple(_s.COEFFICIENT_TYPES) + (np.integer, np.floating, np.complexfloating)
_ofpatch()

ENC = ["JW", "BK", "parity"]


def encode(fop, enc, n):
    if enc == "JW":
        return jordan_wigner(fop)
    if enc == "BK":
        return bravyi_kitaev(fop, n_qubits=n)
    if enc == "parity":
        _ofpatch()
        return of.binary_code_transform(fop, of.parity_code(n))
    raise ValueError(enc)


def max_mean_weight(qop):
    ws = [len(t) for t in qop.terms if len(t) > 0]
    return (max(ws) if ws else 0, (sum(ws) / len(ws)) if ws else 0.0)


def dense(qop, n):
    return np.asarray(get_sparse_operator(qop, n_qubits=n).todense())


def dla_dim(gen_mats, cap=800):
    """Real dim of the Lie algebra generated by {i*M} (M Hermitian) under commutator."""
    def vec(A):
        return np.concatenate([A.real.ravel(), A.imag.ravel()]).astype(float)
    basis, Q, queue = [], [], []

    def add(A):
        v = vec(A)
        for q in Q:
            v = v - (q @ v) * q
        nv = np.linalg.norm(v)
        if nv > 1e-7:
            Q.append(v / nv); basis.append(A); return True
        return False

    for M in gen_mats:
        if add(1j * M):
            queue.append(basis[-1])
    while queue:
        A = queue.pop()
        for B in list(basis):
            C = A @ B - B @ A
            if np.linalg.norm(C) < 1e-9:
                continue
            if add(C):
                queue.append(basis[-1])
                if len(basis) >= cap:
                    return ">=%d" % cap
    return len(basis)


def two_sre(psi, n):
    """2-stabilizer-Renyi-entropy of pure state psi (n qubits). M2 = -log2( sum_P <P>^4 / 2^n )."""
    d = 1 << n
    idx = np.arange(d)
    pc = np.array([bin(b).count("1") for b in range(d)])
    s2 = s4 = 0.0
    for x in range(d):
        cpsi_shift = np.conjugate(psi[idx ^ x])
        for z in range(d):
            signs = 1.0 - 2.0 * (pc[idx & z] & 1)        # (-1)^{popcount(b&z)}
            val = cpsi_shift @ (signs * psi)             # <X^x Z^z>
            phase = (1j) ** (bin(x & z).count("1"))      # Hermitian-Pauli phase
            exp = (phase * val).real
            s2 += exp * exp
            s4 += exp ** 4
    assert abs(s2 - d) < 1e-6 * d, "Parseval failed: sum <P>^2=%.4f != 2^n=%d" % (s2, d)
    return -np.log2(s4 / d)


def ground_state(qop, n):
    H = dense(qop, n)
    w, V = np.linalg.eigh(H)
    return V[:, 0]


# ---------------- models (return n_qubits, hermitian generators, full Hamiltonian) -------------
def free_fermion_chain(L):
    n = L
    gens, H = [], FermionOperator()
    for i in range(L - 1):
        h = FermionOperator("%d^ %d" % (i, i + 1)) + FermionOperator("%d^ %d" % (i + 1, i))
        gens.append(h); H += -1.0 * h
    for i in range(L):
        ni = FermionOperator("%d^ %d" % (i, i))
        gens.append(ni)
        H += 0.37 * (i - (L - 1) / 2.0) * ni             # non-uniform potential -> unique ground state
    return n, gens, H


def hubbard_chain(L, t=1.0, U=3.0):
    n = 2 * L
    up = lambda i: 2 * i
    dn = lambda i: 2 * i + 1
    gens, H = [], FermionOperator()
    for i in range(L - 1):
        for s in (up, dn):
            h = FermionOperator("%d^ %d" % (s(i), s(i + 1))) + FermionOperator("%d^ %d" % (s(i + 1), s(i)))
            gens.append(h); H += -t * h
    for i in range(L):
        g = FermionOperator("%d^ %d %d^ %d" % (up(i), up(i), dn(i), dn(i)))   # n_up n_dn
        gens.append(g); H += U * g
    for m in range(n):
        H += 0.11 * (m - (n - 1) / 2.0) * FermionOperator("%d^ %d" % (m, m))
    return n, gens, H


def molecular_like(N, seed=1):
    """Generic all-to-all 2-body fermionic Hamiltonian (chemistry-like NON-local structure)."""
    rng = np.random.default_rng(seed)
    H = FermionOperator()
    for p in range(N):
        for q in range(p + 1, N):
            H += rng.normal() * (FermionOperator("%d^ %d" % (p, q)) + FermionOperator("%d^ %d" % (q, p)))
            H += rng.normal() * FermionOperator("%d^ %d %d^ %d" % (p, p, q, q))   # n_p n_q
    return N, H


def run_instance(name, n, gens, H, do_sre=True):
    print("\n=== %s  (n=%d qubits) ===" % (name, n))
    print("%-8s %8s %8s %8s %10s" % ("enc", "wmax", "wmean", "DLAdim", "2-SRE"))
    res = {}
    for enc in ENC:
        try:
            Hq = encode(H, enc, n)
        except Exception as e:
            print("%-8s  encode failed: %s" % (enc, e)); continue
        wmax, wmean = max_mean_weight(Hq)
        gmats = [dense(encode(g, enc, n), n) for g in gens]
        d = dla_dim(gmats)
        sre = two_sre(ground_state(Hq, n), n) if do_sre else None
        res[enc] = (wmax, wmean, d, sre)
        print("%-8s %8d %8.2f %8s %10s" % (enc, wmax, wmean, str(d),
              ("%.5f" % sre) if sre is not None else "-"))
    return res


def verdict(res):
    dims = {r[2] for r in res.values()}
    sres = [r[3] for r in res.values() if r[3] is not None]
    wmaxs = {r[0] for r in res.values()}
    dla_inv = (len(dims) == 1)
    sre_inv = (len(sres) <= 1) or (max(sres) - min(sres) < 1e-4)
    wt_cov = (len(wmaxs) > 1)
    print("  -> DLA invariant: %s | SRE invariant: %s | weight covariant: %s"
          % (dla_inv, sre_inv, wt_cov))
    return dla_inv, sre_inv, wt_cov


if __name__ == "__main__":
    print("######## PART A: invariance vs covariance (small n, exact) ########")
    summ = []
    for name, (n, g, H) in {
        "free-fermion chain L=6": free_fermion_chain(6),
        "Fermi-Hubbard 1D L=2 (4 modes)": hubbard_chain(2),
    }.items():
        r = run_instance(name, n, g, H)
        summ.append((name, verdict(r)))

    print("\n######## PART B: does the weight-based verdict FLIP? (weight only) ########")
    print("threshold: weight-simulable iff max Pauli weight <= 2*log2(n)")
    print("%-6s %4s %8s %8s %8s   %s" % ("model", "n", "thr", "JW wmax", "BK wmax", "verdict JW / BK"))
    flips = 0
    for L in range(2, 8):
        n, g, H = hubbard_chain(L)
        thr = 2 * np.log2(n)
        jw = max_mean_weight(encode(H, "JW", n))[0]
        bk = max_mean_weight(encode(H, "BK", n))[0]
        vj = "simulable" if jw <= thr else "HARD"
        vb = "simulable" if bk <= thr else "HARD"
        flip = "  <== FLIP" if vj != vb else ""
        if vj != vb:
            flips += 1
        print("%-6s %4d %8.2f %8d %8d   %-9s / %-9s%s" % ("Hubbard", n, thr, jw, bk, vj, vb, flip))

    print("\n######## PART C: NON-local (chemistry-like all-to-all) -- does the verdict FLIP? ########")
    print("%-10s %4s %8s %8s %8s   %s" % ("model", "N", "thr", "JW wmax", "BK wmax", "verdict JW / BK"))
    flips_c = 0
    for N in range(6, 17, 2):
        _, H = molecular_like(N)
        thr = 2 * np.log2(N)
        jw = max_mean_weight(encode(H, "JW", N))[0]
        bk = max_mean_weight(encode(H, "BK", N))[0]
        vj = "simulable" if jw <= thr else "HARD"
        vb = "simulable" if bk <= thr else "HARD"
        flip = "  <== FLIP" if vj != vb else ""
        if vj != vb:
            flips_c += 1
        print("%-10s %4d %8.2f %8d %8d   %-9s / %-9s%s" % ("molecular", N, thr, jw, bk, vj, vb, flip))

    print("\n######## GATE SUMMARY ########")
    allinv = all(d and s for _, (d, s, _) in summ)
    allcov = all(c for _, (_, _, c) in summ)
    print("0b correctness (DLA & SRE invariant across encodings): %s" % ("PASS" if allinv else "FAIL"))
    print("0c/covariance (Pauli weight changes with encoding):    %s" % ("PASS" if allcov else "FAIL"))
    print("0d substance (verdict flips; local Hubbard=%d, NON-local molecular=%d): %s"
          % (flips, flips_c, "PASS" if (flips + flips_c) > 0 else "FAIL"))
