"""T-A: faithfulness is the trainability boundary.

Re-encoding (JW <-> BK <-> parity) is a FAITHFUL *-isomorphism of the fermionic operator
algebra: it preserves the dynamical Lie algebra g exactly (dim g identical across the orbit),
hence the gradient and the barren-plateau variance. This holds because the map is faithful,
NOT because it is Clifford -- the same is true of any faithful (even nonlinear) encoding.

Symmetry tapering / sector projection is a NON-faithful *-homomorphism: it restricts the
representation to an invariant subspace H_S. The realized algebra is rho_S(g) with
    dim rho_S(g) = dim g - dim ker(rho_S | g)  <=  dim g,
strict EXACTLY when the restriction is non-faithful on g. This is not automatic: whether it
happens is itself an invariant of the physics.

  * Gaussian (free-fermion) ansatz: g = u(n) acts faithfully on every fixed-charge sector, so
    tapering does NOT change dim g (and cannot change trainability).
  * Genuinely interacting ansatz: the full-Fock DLA acts reducibly across charge sectors, so
    tapering IS non-faithful and dim g drops substantially (e.g. 66->36 at n=4, 918->400 at n=6),
    which changes the barren-plateau variance ~ 1/dim g.

Operational rule: re-encoding can NEVER change trainability; only leaving the gauge group (a
non-faithful reduction such as symmetry tapering) can, and only for non-Gaussian ansatze.

Run: python gauge_tapering.py
"""
import numpy as np
from openfermion import FermionOperator
from gauge_micro import encode, dense, dla_dim, ENC
from gauge_dla_scale import free_gens, interacting_gens, dla_dim_pauli, aH


def number_sector(n, m):
    return np.array([b for b in range(1 << n) if bin(b).count("1") == m])


def restrict_dla(gens, n, idx):
    """dim of the algebra generated by the ansatz generators RESTRICTED to a charge sector.

    Dense, but only on the small C(n, n/2)-dimensional sector, so it is cheap even when the
    full-Fock algebra is large.
    """
    mats = [dense(encode(g, "JW", n), n)[np.ix_(idx, idx)] for g in gens]
    return dla_dim(mats, cap=20000)


def full_dla(gens, n):
    return dla_dim_pauli(aH(gens, "JW", n), cap=20000)        # sparse: fast on the full Fock space


def reencode_dims(gens, n):
    return {e: dla_dim_pauli(aH(gens, e, n), cap=20000) for e in ENC}


def pr(*a):
    print(*a, flush=True)


if __name__ == "__main__":
    pr("######## T-A: faithfulness is the trainability boundary ########\n")
    pr("%-14s %-4s | %-26s | %-10s %-16s %-6s" %
       ("family", "n", "dim g across {JW,BK,parity}", "full Fock", "tapered (N=n/2)", "drop"))
    pr("-" * 84)
    for label, gf in (("free/Gaussian", free_gens), ("interacting", interacting_gens)):
        for n in (4, 6):
            gens = gf(n)
            denc = reencode_dims(gens, n)
            inv = "(invariant)" if len(set(denc.values())) == 1 else "(DIFFER!)"
            idx = number_sector(n, n // 2)
            df = full_dla(gens, n)
            dt = restrict_dla(gens, n, idx)
            drop = (df - dt) if isinstance(df, int) and isinstance(dt, int) else "cap"
            pr("%-14s %-4d | %-13s %-12s | %-10s %-16s %-6s" %
               (label, n, str(set(denc.values())), inv, str(df), str(dt), str(drop)))
        pr("")
    pr("-" * 84)
    pr("Re-encoding: dim g identical across the gauge orbit for BOTH families (faithful *-isos).")
    pr("Tapering:    no change for the Gaussian family (faithful on the sector);")
    pr("             a large drop for the interacting family (non-faithful on the sector).")
    pr("So trainability is invariant under re-encoding, and movable only by LEAVING the gauge")
    pr("group -- and only when the ansatz is non-Gaussian. This is the exact 'iff' boundary.")
